
/****** All Variables declared here *******/
export class Utils  {
  isLoginPage:boolean=false;
  USER_VALIDATED:string='User Validation Successfully';
  STATUS_SUCCESS:string='SUCCESS';
  appclient:string='W';
  serviceURL:string='';

  SERVICE_CALL_ERROR=" error";
  SERVICE_CALL_ERROR_CODE="errorcode";
  SERVICE_CALL_INACTIVE="INACTIVE";
  SERVICE_CALL_PAYINIT="PAYINIT";
  SERVICE_CALL_MENU = "menu";
  SERVICE_CALL_APPUSERVO="appuserVo";
  SERVICE_CALL_USERROLES="userRoles";
  SERVICE_CALL_ROLEVO="rolevo";
  SERVICE_CALL_ROLEVO_NAME="name";
  SERVICE_CALL_VERIFICATION_STATUSVO="verificationStatusVo";
  SERVICE_CALL_ORG="org";
  SERVICE_CALL_DEPARTMENT="department";
  SERVICE_CALL_BUSINESS_UNIT="businessunit";
  SERVICE_CALL_ORG_NAME="name";
  SERVICE_CALL_ORG_LOGO="logo";
  SERVICE_CALL_ROLE="role";
  SERVICE_CALL_VERIFIED="VERIFIED";
  SERVICE_CALL_USERMENUS="userMenus";
  SERVICE_CALL_STATUS="status";
  SERVICE_CALL_DATA= "data";
  SERVICE_CALL_PARENT_MENU="parentMenu";
  SERVICE_CALL_NAME="name;";
  totalPages: any;
  pages: any;
  input: any ;
  isLoadingSpin:boolean=false;
  deleted:boolean=false;
  functionName: string;
  deleteName: string;
  userMenuArr: any;
  payFrequency: any=[];
  jobtitles: any=[];
  subSidebarMenuArr: any = [];
  subChildMenuArr: any = [];
  parentChildMenuArray: any=[];
  function_Name: string = "";
  delete_Name: string = "";
  sidebarMenuArr:any=[];
  langList: any = [];
  raceList: any = [];
  raceCodeList: any = [];
  ethCodeList: any;
  nationalityList: any;
  staticCountryData: any;
  staticStateData: any;
  cityList: any;
  stateArr: any;
  countryArr: any;
  curCountryArr: any;
  curStateArr: any;
	ctModStateArr: any;
  ctModCountryArr: any;
	curCityList: any;
  deptListData: any;
  deptEditId: any;
  deptEditSalu: any;
  deptEditGender: any;
  deptEditfName: any;
  deptEditmName: any;
  deptEditlName: any;
  deptEditRel: any;
  deptEditDob: any;
  deptEditAge: any;
  deptViewId: any;
  deptViewSalu: any;
  deptViewfName: any;
  deptViewGender: any;
  deptViewmName: any;
  deptViewlName: any;
  deptViewRel: any;
  deptViewDob: any;
  deptViewAge: any;
  courseList: any;
  certViewCourseName: any;
  certViewOfferedBy: any;
  certViewLevel: any;
  certViewDesc: any;
  certViewName: any;
  certViewIssueDate: any;
  certEditCourseName: any;
  certEditDesc: any;
  certEditLevel: any;
  certEditOfferedBy: any;
  certEditName: any;
  certEditIssueDate: any;
  certId: any;
  certEditId: any;
  eduEditData: any;
  levelcode: any;
  instiName: any;
  uniName: any;
  course: any;
  fromDate: any;
  educationList: any;
  toDate: any;
  fromPer: any;
  SkillList: any;
  cmpLevelAr: any;
  experienceList: any;
  eduLevelAr: any;
  editSkillName: any;
  editSkillExp: any;
  editSkillLastUse: any;
  editSkillLevel: any;
  expCname: any;
  expCweb: any;
  expCdesi: any;
  fromCdate: any;
  toCdate: any;
  expcrfl: any;
  expCrname: any;
  expCcnct: any;
  expCemail: any;
  visaDetailsList: any;
  passNum: any;
  visaNum: any;
  inineSatus: any;
  passIdate: any;
  passEdate: any;
  visaType: any;
  visaIdate: any;
  visaEdate: any;
  inineRSatus: any;
  issueAuth: any;
  iNineFrstatus: any;
  iNineFdate: any;
  disabilityTypeList: any;
  disabilityList: any;
  disabilityname: any ;
  disabilityType: any= "";
  disabilityDesc: any;
  militaryServiceTypeList: any;
  veteranStatusList: any;
  dischargeStatusList: any;
  empSubMenuArr: any = [];
  holidayNameList: any = [];
  grpItemListArr: any = [];
  earnitemArr: any = [];
  deductitemArr: any = [];
  preqitemArr: any = [];
  itemType: any;
  leaveTypeArr: any;
  leaveData: any;
  doclistarr: any = [];
  ploicydocListArr: any;
  payFrequencyarr: any= [];
  pocdata: any = [];
  contactcheckTypeList: any;
  appRatingArr: any = [];
  apprisalType: any;
  managerList: any;
  departmentList: any;
  appconfigmode: any = [];
  buData:any = [];
  sourcevalArr: any;
  fromadd: any = [];
  toAddress: any = [];
  tripname1: any;
  fdate: any;
  tdate: any;
  orgnizationList: any = [];
  roleList: any = [];
  countryList: any = [];
  salutationList: any = [{id:"1",name:"Mr"},{id:"2",name:"Miss"},{id:"3",name:"Mrs"}];
  companiesList: any = [];
  contactTypeList: any = [];
  contactListArray: any = [];
  CREATECONTACT_URL= "contact/createbulkcontacts";
  GETALL_CONTACTS= "contact/getall";
  DELETECONTACT_URL = "contact/delete";
  CREATEACTIVITY_URL = "activity/create";
  UPDATEACTIVITY_URL = "activity/update";
  DELETEACTIVITY_URL = "activity/delete";
  ACTIVITYCREATEDUPDATEDBY_URL="activity/getallcreatedupdatedby";
  UPDATECONTACT_URL = "contact/update";
  GETHIERARCHY_URL = "contact/getparenthierachy";
  GETHIERARCHYSUBCHILD_URL = "contact/gethierachy";
  // GETSTATICDATA_URL = "contact/getstatic";
  GETSTATICDATA_URL = "staticdata/getstatic";
  GETCRITERIAFILTERDATA_URL = "filterby/findbycriteria";
  GETDESIGNATION_URL = "contact/getdesignations";
  GETLOCATIONLIST_URL = "address/getcities";
  GETCONTACTOWNER_URL = "contact/getallcontactowner";
  GETREPORTINGTO_URL = "contact/getallreportingto";
  GETALLCOMPANY_URL = "contactorg/getall";
  CREATEWIDGET_URL = "userwidget/create";
  DELETEWIDGET_URL = "userwidget/delete";
  GETACTIVITYTYPE_URL = "activitytype/getall";
  GETUPDATEDBY_URL = "activity/getallupdatedby";
  CONTACTIMPORT_URL = "import/impcontacts";
  
  contactList = [];
  // activityList:any = [];
  contactName: any;
  name: any;
  contactId: any;
  ds: any = {};
  widgets: any = [];
  id: any;


}
